// <auto-generated />
using System;
using ApplicationDeGestionERP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationDeGestionERP.Migrations
{
    [DbContext(typeof(ApplicationDbContextes))]
    [Migration("20250120130606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleID"));

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionArticle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomArticle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PrixAchat")
                        .HasColumnType("float");

                    b.Property<double>("PrixDeVente")
                        .HasColumnType("float");

                    b.Property<int>("QteStockArticle")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TVA")
                        .HasColumnType("int");

                    b.HasKey("ArticleID");

                    b.HasIndex("CategorieID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Categorie", b =>
                {
                    b.Property<int>("CategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieID"));

                    b.Property<string>("DescriptionCategorie")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategorieID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("AdresseClient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MatriculeFiscaleOuCin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrénomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelephoneClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Facture", b =>
                {
                    b.Property<int>("FactureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactureID"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("datetime2");

                    b.Property<double>("MontantTotalHT")
                        .HasColumnType("float");

                    b.Property<double>("MontantTotalTTC")
                        .HasColumnType("float");

                    b.HasKey("FactureID");

                    b.HasIndex("ClientID");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Fournisseur", b =>
                {
                    b.Property<int>("IDFournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDFournisseur"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("MontantPaye")
                        .HasColumnType("float");

                    b.Property<string>("NomFournisseur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumTelephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("TotalMontantAchete")
                        .HasColumnType("float");

                    b.HasKey("IDFournisseur");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_LigneFacture", b =>
                {
                    b.Property<int>("LigneFactureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LigneFactureID"));

                    b.Property<int>("ArticleID")
                        .HasColumnType("int");

                    b.Property<int>("FactureID")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("LigneFactureID");

                    b.HasIndex("ArticleID");

                    b.HasIndex("FactureID");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Article", b =>
                {
                    b.HasOne("ApplicationDeGestionERP.Models.G_Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Facture", b =>
                {
                    b.HasOne("ApplicationDeGestionERP.Models.G_Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_LigneFacture", b =>
                {
                    b.HasOne("ApplicationDeGestionERP.Models.G_Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationDeGestionERP.Models.G_Facture", "Facture")
                        .WithMany("LignesFacture")
                        .HasForeignKey("FactureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Client", b =>
                {
                    b.Navigation("Factures");
                });

            modelBuilder.Entity("ApplicationDeGestionERP.Models.G_Facture", b =>
                {
                    b.Navigation("LignesFacture");
                });
#pragma warning restore 612, 618
        }
    }
}
